webtalk_init -webtalk_dir D:\\Nate\\dev\\FPGA_stuff\\fpgaProjects\\zybo\\cnc-controller\\firmware\\zynq\\cnc-controller.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2017-10-04 19:51:44" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "210903556_0_0_841" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "7f5gdtpfa1m938hbud7h5pik3l" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.2_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3500 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1507150199168" -context "sdk\\\\hardware/1507150199168"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1507150199168"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1507150199168"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1507150199168"
webtalk_add_data -client sdk -key VivadoVersion -value "2017.2" -context "sdk\\\\hardware/1507150199168"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1507150199168"
webtalk_add_data -client sdk -key Device -value "7z010" -context "sdk\\\\hardware/1507150199168"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1507150199168"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1507150199168"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1507150199168"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1507150199168"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1507171904838"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1507171904838"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1507171904838"
webtalk_add_data -client sdk -key DebugCount -value "2" -context "sdk\\\\bsp/1507171904838"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1507171904838"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1507171904838"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1507171904838"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1507171904838"
webtalk_transmit -clientid 667768487 -regid "210903556_0_0_841" -xml D:\\Nate\\dev\\FPGA_stuff\\fpgaProjects\\zybo\\cnc-controller\\firmware\\zynq\\cnc-controller.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\Nate\\dev\\FPGA_stuff\\fpgaProjects\\zybo\\cnc-controller\\firmware\\zynq\\cnc-controller.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\Nate\\dev\\FPGA_stuff\\fpgaProjects\\zybo\\cnc-controller\\firmware\\zynq\\cnc-controller.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
