# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Nate/dev/FPGA_stuff/fpgaProjects/zybo/ip_repo/pl_pwm/edit_pl_pwm_v1_0.cache/wt [current_project]
set_property parent.project_path D:/Nate/dev/FPGA_stuff/fpgaProjects/zybo/ip_repo/pl_pwm/edit_pl_pwm_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  d:/Nate/dev/FPGA_stuff/fpgaProjects/zybo/ip_repo/pl_pwm/pl_pwm_1.0
  d:/Nate/dev/FPGA_stuff/fpgaProjects/zybo/ip_repo/pl_pwm/pl_pwm_1.0
} [current_project]
set_property ip_output_repo d:/Nate/dev/FPGA_stuff/fpgaProjects/zybo/ip_repo/pl_pwm/edit_pl_pwm_v1_0.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  D:/Nate/dev/FPGA_stuff/fpgaProjects/zybo/ip_repo/pl_pwm/pl_pwm_1.0/hdl/pl_pwm_v1_0_S00_AXI.vhd
  D:/Nate/dev/FPGA_stuff/fpgaProjects/zybo/ip_repo/pl_pwm/edit_pl_pwm_v1_0.srcs/pwm_controller.vhd
  D:/Nate/dev/FPGA_stuff/fpgaProjects/zybo/ip_repo/pl_pwm/pl_pwm_1.0/hdl/pl_pwm_v1_0.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Nate/dev/FPGA_stuff/fpgaProjects/zybo/ip_repo/pl_pwm/edit_pl_pwm_v1_0.srcs/constrs_1/zybo_constraints.xdc
set_property used_in_implementation false [get_files D:/Nate/dev/FPGA_stuff/fpgaProjects/zybo/ip_repo/pl_pwm/edit_pl_pwm_v1_0.srcs/constrs_1/zybo_constraints.xdc]


synth_design -top pl_pwm_v1_0 -part xc7z010clg400-1


write_checkpoint -force -noxdef pl_pwm_v1_0.dcp

catch { report_utilization -file pl_pwm_v1_0_utilization_synth.rpt -pb pl_pwm_v1_0_utilization_synth.pb }
