#ifndef INCLUDE_TASK_PRIORITIES_H
#define INCLUDE_TASK_PRIORITIES_H

#define DEVICE_DISCOVERY_TASK_PRIORITY 					7
#define ETHERNET_HANDLING_TASK_PRIORITY 				6
#define STAGE_COMMAND_QUEUE_PROCESSING_TASK_PRIORITY 	5

#endif
